# Generated by Django 5.1.3 on 2024-11-16 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_Number', models.CharField(max_length=50)),
                ('Whatsapp_Number', models.CharField(max_length=50)),
                ('Company_Name', models.CharField(max_length=50)),
                ('Company_Registration_Number', models.IntegerField()),
                ('Company_VAT_Number', models.CharField(max_length=50)),
                ('Company_Address', models.CharField(max_length=50)),
                ('Role', models.CharField(max_length=50)),
                ('Designation', models.CharField(max_length=50)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
