# Generated by Django 5.1.3 on 2024-11-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='Company_Registration_Number',
            field=models.CharField(max_length=50),
        ),
    ]
